lib/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

mysite/urls.py
# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static


from polls.views import index
from login.views import *

urlpatterns = [
    url(r'', include('places.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^places/', include('places.urls')),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),
    #url(r'^accounts/login/$', auth_views.login, name="login"),  # If user is not login it will redirect to login page
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='place/login.html'), name="login"),
    url(r'^register/$', register, name="register"),
    url(r'^register/success/$', register_success),
    url(r'^home/$', home),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.conf.urls import url, include

from . import views

from views import PlaceOffersList

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'places', views.PlaceViewSet, base_name='places')
router.register(r'offers', views.OfferViewSet, base_name='offers')
router.register(r'placeOffers', views.PlaceOffersList, 'place_offers')
router.register(r'appUsers', views.AppUserViewSet)
router.register(r'placeSubscriber', views.PlaceSubscriberViewSet)

urlpatterns = [
    url(r'^$', views.place_list, name='list_place'),
    url(r'^category/create/$', views.category_create, name='create_category'),
    url(r'^category/list/$', views.category_list, name='list_category'),
    url(r'^place/list/$', views.place_list, name='list_place'),
    url(r'^place/create/$', views.place_create, name='create_place'),
    url(r'^place/update/(?P<pk>\d+)$', views.place_update, name='update_place'),
    #url(r'^place/(?P<pk>\d+)$', views.PlaceDetailView.as_view(), name='detail_place'),
    url(r'^place/(?P<place_id>\d+)$', views.place_detail, name='detail_place'),
    url(r'^place/(?P<pk>\d+)/barcode', views.PlaceDetailBarcodeView.as_view(), name='detail_place_barcode'),
    url(r'^place/delete/(?P<pk>\d+)/$', views.place_delete, name='delete_place'),
    # Offer urls
    url(r'^place/(?P<pk>\d+)/offer/create/$', views.add_offer_to_place, name='add_offer_to_place'),
    url(r'^offer/create/$', views.offer_create, name='create_offer'),
    url(r'^offer/(?P<pk>\d+)$', views.OfferDetailView.as_view(), name='detail_offer'),
    url(r'^offer/delete/(?P<pk>\d+)/$', views.offer_delete, name='delete_offer'),
    url(r'^placeSubscriber/delete/$', views.place_subscriber_delete, name='delete_place_subscriber'),
    url(r'^places/$', views.PlaceSubscriberViewSet, name='list_places_api'),
    #url(r'^api/placeSubscriber/$', views.PlaceSubscriberDetail.as_view()),
    #url(r'^api/place/(?P<place_id>.+)/offers/$', PlaceOffersList.as_view(), name='place_offer_view'),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

places/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from rest_framework.validators import UniqueValidator
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    def __str__(self):
        return self.name


class AppUser(models.Model):
    full_name = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    facebook_id = models.CharField(max_length=200, unique=True, error_messages={'unique':"This User Already Registered"})
    profile_picture = models.CharField(max_length=500)
    push_token = models.CharField(max_length=200, default=0)
    ionic_id = models.CharField(max_length=200, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_blocked = models.BooleanField(default=False)
    #my_places = models.ManyToManyField(Place, through='PlaceSubscriber')

    def __str__(self):
        return self.full_name


class Place(models.Model):
    PLACE_TYPES = (
		(1, 'Restaurant'),
		(2, 'Bar'),
		(3, 'Bar and Restaurant'),
    )
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    #city_id = models.CharField(max_length=200)
    place_type_id = models.IntegerField(default=1, choices=PLACE_TYPES)
    #image = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/')
    image_thumbnail = models.ImageField(upload_to='images/thumbnails')
    image_cover = models.ImageField(upload_to='images/covers')
    latitude = models.CharField(max_length=200)
    longitude = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='places', default=1)
    subscribers = models.ManyToManyField(AppUser, through='PlaceSubscriber')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):              # __unicode__ on Python
   		return self.name


class Offer(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    place = models.ForeignKey(Place, related_name='offers', on_delete=models.CASCADE)
    offer_type = models.IntegerField(default=0)
    image_thumbnail = models.ImageField(upload_to='images/thumbnails')
    image = models.ImageField(upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
    	return self.name

	class Meta:
		ordering = ('name',)


class PlaceSubscriber(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    date_subscribed = models.DateTimeField(editable=False, default=timezone.now)

    class Meta:
        unique_together = ('place', 'user')

    def __str__(self):
        return '%s %s' % (self.place, self.user)

login/forms.py
# files.py
import re
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class RegistrationForm(forms.Form):
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, )),
                                label=_("Username"), error_messages={
            'invalid': _("This value must contain only letters, numbers and underscores.")})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email address"))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)),
        label=_("Password (again)"))

    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data

login/views.py
# views.py
from login.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render




@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'],
                email=form.cleaned_data['email'],
                is_staff=True
            )
            return HttpResponseRedirect('/register/success/')
    else:
        form = RegistrationForm()
    variables = RequestContext(request, {
        'form': form
    })
    return render(request, "registration/register.html",  {'form': form})


def register_success(request):
    return render_to_response(
        'registration/success.html',
    )


def logout_page(request, *args, **kwargs):
    logout(request, *args, **kwargs)


@login_required
def home(request):
    return render_to_response(
        'home.html',
        {'user': request.user}
    )

places/templates/place/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block head %}Login{% endblock %}
{% block content %}

        <!-- LOGIN FORM -->
		<!--===================================================-->
		<div class="cls-content">
		    <div class="cls-content-sm panel">
		        <div class="panel-body">
		            <div class="mar-ver pad-btm">
		                <h1 class="h3">Places Login</h1>
		                <p>Sign In to your account</p>
		            </div>
		            <form method="post" action="." class="form-signin">{% csrf_token %}
		                <div class="form-group">
                            <input id="id_username" type="text" name="username" class="form-control" placeholder="Email" autofocus>
		                </div>
		                <div class="form-group">
                            <input type="password" id="id_password" name="password" class="form-control" placeholder="Password" >
		                </div>
		                <div class="checkbox pad-btm text-left">
		                    <input id="demo-form-checkbox" class="magic-checkbox" type="checkbox">
		                    <label for="demo-form-checkbox">Remember me</label>
		                </div>
		                <button class="btn btn-primary btn-lg btn-block" type="submit">Sign In</button>
                        <input type="hidden" name="next" value="/places/place/list" />
		            </form>
		        </div>

		        <div class="pad-all">
		            <a href="#" class="btn-link mar-rgt">Forgot password ?</a>
		            <a href="{% url 'register' %}" class="btn-link mar-lft">Create a new account</a>
		        </div>
		    </div>
		</div>
		<!--===================================================-->



    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

{% endblock %}

places/templates/place/place_create.html
{% extends "base.html" %}


{% block title %}
    <!--Page Title-->
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <div id="page-title">
        <h1 class="page-header text-overflow">Places</h1>


    </div>
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <!--End page title-->

{% endblock %}
{% block head %}Create Place{% endblock %}
{% block head_subtitle %}Here you can create a new place{% endblock %}
{% block breadcrumb %}


<!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <ol class="breadcrumb">
                    <li>
                                            <i class="fa fa-home"></i>
                                            <a href="{% url 'list_place' %}">Home</a>
                                        </li>

                                        <li>
                                            <i class="fa fa-list"></i>
                                            <a href="{% url 'list_place' %}">List Places</a>
                                        </li>

                                        <li class="active">
                                            <i class="fa fa-table"></i> Create Place
                                        </li>
                </ol>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End breadcrumb-->

{% endblock %}




{% block content %}





    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-long-arrow-right fa-fw"></i> Places</h3>
            </div>
            <div class="panel-body">

                {% if place_form.errors %}
                <div class="alert alert-danger">
                  <strong>Alert!</strong> Please validate all fields before submitting.
                </div>
                {% endif %}

                {% load crispy_forms_tags %}
                {% crispy place_form %}



            </div>
        </div>
    </div>


<script>
function showAlert() {
    alert("Nice");
}
</script>



{% endblock %}

places/templates/place/place_detail.html
{% extends "base.html" %}






{% block breadcrumb %}

<ol class="breadcrumb">
                                        <li>
                                            <i class="fa fa-home"></i>
                                            <a href="{% url 'list_place' %}">Home</a>
                                        </li>

                                        <li>
                                            <i class="fa fa-list"></i>
                                            <a href="{% url 'list_place' %}">List Places</a>
                                        </li>

                                        <li class="active">
                                            <i class="fa fa-table"></i> Place Detail
                                        </li>
                                    </ol>

{% endblock %}


{% block title %}
    {{ place.name }}
{% endblock %}
{% block head %}{{ place.name }}{% endblock %}
{% block head_subtitle %}{{ place.description }}{% endblock %}

{% block content %}



        <div class="col-lg-12">




            <div class="panel panel-default">

                            <div class="panel-body">

                                <div class="panel panel-default">
                                  <div class="panel-body">
                                    <ul class="nav nav-pills pull-left">
                                        <li role="presentation"><a href="#subscribers">Subscribers ({{ place.subscribers.count }})</a></li>
                                        <li role="presentation"><a href="#offers">Offers ({{ place.offers.count }})</a></li>
                                        <li role="presentation"><a href="#">Check-ins (0)</a></li>
                                        <li role="presentation"><a href="{% url 'detail_place_barcode' place.id %}">Code Scan</a></li>
                                        <li role="presentation" class="disabled"><a href="#">Send Broadcast</a></li>
                                    </ul>

                                      <div class="pull-right">
                                            <a href="#" class="btn btn-primary btn-sm" onclick="updatePlace({{ place.id }}); return false;">Edit</a>
                                            <a href="#" class="btn btn-danger btn-sm" onclick="deletePlace({{ place.id }}); return false;  ">Delete</a>
                                          </div>
                                  </div>
                                </div>

                                <div class="panel panel-default">
                                    <div class="panel-body">
                                    <div class="row form-group">
                                        <div class="col-md-6"> <b>Name: </b>{{ place.name }} </div>
                                        <div class="col-md-6"> <b>Type: </b>{{ place.get_place_type_id_display }} </div>

                                        </div>

                                    <div class="row form-group">
                                        <div class="col-md-6"> <b>Phone number: </b>{{ place.phone_number }} </div>
                                        <div class="col-md-6"> <b>Email: </b>{{ place.email }} </div>

                                        </div>

                                    <div class="row form-group">
                                        <div class="col-md-6"> <b>Description: </b>{{ place.description }} </div>
                                        <div class="col-md-6"> <b>Address: </b>{{ place.address }} </div>
                                        </div>

                                    <div class="row">
                                        <div class="col-md-4"> <b>Thumbnail: </b>
                                        <img class="img-responsive" width="200" height="200" src="{{ place.image_thumbnail.url }}" alt="Card image cap"> </div>
                                        <div class="col-md-4"> <b>Image: </b>
                                        <img class="img-responsive" width="200" height="200" src="{{ place.image.url }}" alt="Card image cap"> </div>
                                        <div class="col-md-4"> <b>Cover Image: </b>
                                        <img class="img-responsive" src="{{ place.image_cover.url }}" alt="Card image cap"> </div>

                                        </div>

                                    <p class="card-text">

                                    </p>
                                    <b>Location:</b>
                                    <div id="map" style="width:100%;height:300px"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

            <br/>

            <div class="panel panel-default" id="offers">
                <div class="panel-heading">
                    <div class="panel-heading clearfix">
                      <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Offers ({{ place.offers.count }})</h4>
                          <div class="pull-right">
                            <a href="{% url 'add_offer_to_place' pk=place.pk %}" class="btn btn-success btn-sm"><i class="fa fa-plus fa-fw"></i></a>
                          </div>
                    </div>
                </div>
                <div class="panel-body">

                    <div class="list-group">
                    {% for o in place.offers.all %}

                        <a href="{% url 'detail_offer' o.id %}" class="list-group-item clearfix">
                                <span class="pull-left">
                                    {{ forloop.counter }}. &emsp; <strong>{{ o.name }}</strong>
                                </span>
                                <span class="pull-right">
                                  <span class="btn btn-xs btn-primary" onclick="updatePlace({{ place.id }}); return false;">Edit</span>
                                    <span class="btn btn-xs btn-danger" onclick="deleteOffer({{ o.id }}); return false;  ">
                                        Delete
                                    </span>

                                  </button>
                                </span>

                        </a>








                    {% endfor %}
                    </div>



                </div>

            </div>

            <div class="panel panel-default" id="subscribers">
                <div class="panel-heading">
                    <div class="panel-heading clearfix">
                      <h4 class="panel-title pull-left" >Subscribers ({{ place.subscribers.count }})</h4>
                          <div class="pull-right">
                            <a href="{% url 'add_offer_to_place' pk=place.pk %}" class="btn btn-success btn-sm" ><span>Create</span></a>
                          </div>
                    </div>
                </div>
                <div class="panel-body">

                    <div class="list-group">
                    <!-- TODO fix the placesubscriber date subscribed and add to the view -->

                    {% for placeSubscriber in placeSubscribers %}

                        <a href="#" class="list-group-item clearfix">
                                <span class="pull-left">
                                    {{ forloop.counter }}. &emsp;
                                </span>
                                <span class="pull-left">
                                    <strong>{{ placeSubscriber.user__full_name }}</strong>
                                    <p>Email: <i>{{ placeSubscriber.user__email }}</i> | Date Subscribed: <i> {{ placeSubscriber.date_subscribed }} </i> </p>
                                </span>
                                <span class="pull-right">
                                  <span class="btn btn-xs btn-primary" onclick="sendPushNotificationToUser('{{ placeSubscriber.user__ionic_id }}'); return false;">Send Message</span>
                                    <span class="btn btn-xs btn-danger" onclick="deletePlaceUser({{ place.id }}, {{ placeSubscriber.pk }}); return false;  ">
                                        Unsubscribe
                                    </span>

                                  </button>
                                </span>

                        </a>








                    {% endfor %}
                    </div>



                </div>

            </div>




        </div>




<script>
function myMap() {
  var myCenter = new google.maps.LatLng({{ place.latitude }},{{ place.longitude }});
  var mapCanvas = document.getElementById("map");
  var mapOptions = {center: myCenter, zoom: 14, scrollwheel: false,};
  var map = new google.maps.Map(mapCanvas, mapOptions);
  var marker = new google.maps.Marker({position:myCenter});
  marker.setMap(map);
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCmz7oHEd5LqSGdal0vtfWUOkxn9GSUKt4&callback=myMap"></script>


<script>

    function deletePlace(id) {
        var ask = window.confirm("Are you sure you want to delete this post?");
        if (ask) {
            //window.alert("This post was successfully deleted.");

            window.location.replace('/places/place/delete/'+id);

        }
    }

    function updatePlace(id) {
         window.location.replace('/places/place/update/'+id);
    }


    function deleteOffer(id) {
        var ask = window.confirm("Are you sure you want to delete this offer?");
        if (ask) {
            //window.alert("This post was successfully deleted.");

            window.location.replace('/places/offer/delete/'+id);

        }
    }


    function deletePlaceUser(placeId, userId){
        var ask = window.confirm("Are you sure you want to unsubscribe this user from your place?");
        if (ask) {
            //window.alert("This post was successfully deleted.");

            window.location.replace('/places/placeSubscriber/delete/?place_id='+placeId+'&user_id='+userId);

        }
    }

    function sendPushNotificationToUser(ionic_id){

        var message = prompt("Please enter the push notification message", "Message");


        var jsonplace = {
                      "user_ids": [ionic_id],
                      "profile": "placesappdev",
                      "notification": {
                        "title": "Places App",
                        "message": message,
                        "android": {
                          "title": "{{ place.name }}",
                          "message": message
                        },
                        "ios": {
                          "title": "Places App",
                          "message": message
                        }
                      }
                    }


        if (message != null) {
            $.ajax({
                url: 'https://api.ionic.io/push/notifications',
                type: 'post',
                data: JSON.stringify(jsonplace),
                headers: {
                    "Accept" : "application/json; charset=utf-8",
                    "Content-Type": "application/json; charset=utf-8",
                    "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiYjZkM2U1OC02NTRiLTQxNjUtYWVlYy01MTQ5YmU2Y2FjYWYifQ.qY2CNGV4ffSCgGt2zO262b0OBgp_34rsxxu5EZhWtgM"
                },
                dataType: 'json',
                success: function (data) {
                    console.info(data);
                }
            });

        }
    }



</script>


{% endblock %}

places/templates/place/place_detail_barcode.html
{% extends "base.html" %}






{% block breadcrumb %}

<ol class="breadcrumb">
                                        <li>
                                            <i class="fa fa-home"></i>
                                            <a href="{% url 'list_place' %}">Home</a>
                                        </li>

                                        <li>
                                            <i class="fa fa-list"></i>
                                            <a href="{% url 'list_place' %}">List Places</a>
                                        </li>

                                        <li class="active">
                                            <i class="fa fa-table"></i>
                                            <a href="{% url 'detail_place' object.pk %}"> {{ object.name }}</a>
                                        </li>

                                        <li class="active">
                                            <i class="fa fa-tags"></i> Code Scan
                                        </li>
                                    </ol>

{% endblock %}


{% block title %}
    {{ object.name }}
{% endblock %}
{% block head %}{{ object.name }}{% endblock %}
{% block head_subtitle %}Scan code to Check-in{% endblock %}

{% block content %}




<div class="row">
        <div class="col-lg-6">




            <div class="panel panel-default">

                            <div class="panel-heading">Check-ins QR Code</div>
                            <div class="panel-body" style="text-align: center;">
                                <div class="results">


                                    <p><img src="http://chart.apis.google.com/chart?cht=qr&amp;chs=400x400&amp;chl=%7B%22place_id%22%3A%20%22{{object.id}}%22%7D&amp;chld=H|0" alt="QR Code"></p>
                                    <span class="btn btn-xs btn-primary" onclick="sendData(); return false;">Edit</span>
                                </div>



                            </div>





            </div>

        </div>

        <div class="col-lg-6">




            <div class="panel panel-default">

                <div class="panel-heading">Today Check-ins</div>
                <div class="panel-body" style="text-align: center;">

                    <ul id="checkins" class="list-group">
                      <!-- Conatct Object li.list-group-item.contact will be added here by js -->
                    </ul>

                </div>





            </div>

        </div>

</div>





<script src="https://www.gstatic.com/firebasejs/4.2.0/firebase.js"></script>
<script>
  // Initialize Firebase
  var config = {
    apiKey: "AIzaSyCOo5pdonGa7fx2rCwALD4h7Tnf3k8rnXc",
    authDomain: "placesweb-158223.firebaseapp.com",
    databaseURL: "https://placesweb-158223.firebaseio.com",
    projectId: "placesweb-158223",
    storageBucket: "placesweb-158223.appspot.com",
    messagingSenderId: "928811050103"
  };
  firebase.initializeApp(config);
</script>
<script>
function sendData() {
         // Get a reference to the database service
        firebase.database().ref('checkins/').push({
            place_id: "1",
            facebook_id: "123"
          });
    }

//var dbRef = new Firebase("https://contactb.firebaseio.com/");
var contactsRef = firebase.database().ref('checkins/');

//load older conatcts as well as any newly added one...
contactsRef.on("child_added", function(snap) {
  //console.log("added", snap.key(), snap.val());
  $('#checkins').prepend(checkinHtmlFromObject(snap.val()));
});

//prepare conatct object's HTML
function checkinHtmlFromObject(checkin){
  console.log( checkin );
  var html = '';
  html += '<li class="list-group-item clearfix">';
    html += '<span class="pull-left">';
      html += "<img src='http://graph.facebook.com/"+ checkin.facebook_id +"/picture?type=small' class='img-circle' alt='Facebook Profile Picture' >";
      html +=  ' ' + checkin.full_name;
    html += '</span>';
  html += '</li>';
  return html;
}

</script>

{% endblock %}