lib/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

mysite/urls.py
# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static


from polls.views import index
from login.views import *

urlpatterns = [
    url(r'', include('places.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^places/', include('places.urls')),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),
    #url(r'^accounts/login/$', auth_views.login, name="login"),  # If user is not login it will redirect to login page
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='place/login.html'), name="login"),
    url(r'^register/$', register, name="register"),
    url(r'^register/success/$', register_success),
    url(r'^home/$', home),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.conf.urls import url, include

from . import views

from views import PlaceOffersList

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'places', views.PlaceViewSet, base_name='places')
router.register(r'offers', views.OfferViewSet, base_name='offers')
router.register(r'placeOffers', views.PlaceOffersList, 'place_offers')
router.register(r'appUsers', views.AppUserViewSet)
router.register(r'placeSubscriber', views.PlaceSubscriberViewSet)

urlpatterns = [
    url(r'^$', views.place_list, name='list_place'),
    url(r'^category/create/$', views.category_create, name='create_category'),
    url(r'^category/list/$', views.category_list, name='list_category'),
    url(r'^place/list/$', views.place_list, name='list_place'),
    url(r'^place/create/$', views.place_create, name='create_place'),
    url(r'^place/update/(?P<pk>\d+)$', views.place_update, name='update_place'),
    #url(r'^place/(?P<pk>\d+)$', views.PlaceDetailView.as_view(), name='detail_place'),
    url(r'^place/(?P<place_id>\d+)$', views.place_detail, name='detail_place'),
    url(r'^place/(?P<pk>\d+)/barcode', views.PlaceDetailBarcodeView.as_view(), name='detail_place_barcode'),
    url(r'^place/delete/(?P<pk>\d+)/$', views.place_delete, name='delete_place'),
    # Offer urls
    url(r'^place/(?P<pk>\d+)/offer/create/$', views.add_offer_to_place, name='add_offer_to_place'),
    url(r'^offer/create/$', views.offer_create, name='create_offer'),
    url(r'^offer/(?P<pk>\d+)$', views.OfferDetailView.as_view(), name='detail_offer'),
    url(r'^offer/delete/(?P<pk>\d+)/$', views.offer_delete, name='delete_offer'),
    url(r'^placeSubscriber/delete/$', views.place_subscriber_delete, name='delete_place_subscriber'),
    url(r'^places/$', views.PlaceSubscriberViewSet, name='list_places_api'),
    #url(r'^api/placeSubscriber/$', views.PlaceSubscriberDetail.as_view()),
    #url(r'^api/place/(?P<place_id>.+)/offers/$', PlaceOffersList.as_view(), name='place_offer_view'),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

places/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from rest_framework.validators import UniqueValidator
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    def __str__(self):
        return self.name


class AppUser(models.Model):
    full_name = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    facebook_id = models.CharField(max_length=200, unique=True, error_messages={'unique':"This User Already Registered"})
    profile_picture = models.CharField(max_length=500)
    push_token = models.CharField(max_length=200, default=0)
    ionic_id = models.CharField(max_length=200, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_blocked = models.BooleanField(default=False)
    #my_places = models.ManyToManyField(Place, through='PlaceSubscriber')

    def __str__(self):
        return self.full_name


class Place(models.Model):
    PLACE_TYPES = (
		(1, 'Restaurant'),
		(2, 'Bar'),
		(3, 'Bar and Restaurant'),
    )
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    #city_id = models.CharField(max_length=200)
    place_type_id = models.IntegerField(default=1, choices=PLACE_TYPES)
    #image = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/')
    image_thumbnail = models.ImageField(upload_to='images/thumbnails')
    image_cover = models.ImageField(upload_to='images/covers')
    latitude = models.CharField(max_length=200)
    longitude = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='places', default=1)
    subscribers = models.ManyToManyField(AppUser, through='PlaceSubscriber')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):              # __unicode__ on Python
   		return self.name


class Offer(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    place = models.ForeignKey(Place, related_name='offers', on_delete=models.CASCADE)
    offer_type = models.IntegerField(default=0)
    image_thumbnail = models.ImageField(upload_to='images/thumbnails')
    image = models.ImageField(upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
    	return self.name

	class Meta:
		ordering = ('name',)


class PlaceSubscriber(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    date_subscribed = models.DateTimeField(editable=False, default=timezone.now)

    class Meta:
        unique_together = ('place', 'user')

    def __str__(self):
        return '%s %s' % (self.place, self.user)

places/templates/offer/offer_create.html
{% extends "base.html" %}




{% block title %}Create Offer{% endblock %}
{% block head %}Create Offer{% endblock %}
{% block head_subtitle %}Here you can create a offers for your place{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="{% url 'list_place' %}">Home</a>
        </li>

        <li>
            <i class="fa fa-list"></i>
            <a href="{% url 'detail_place' place.pk %}"> {{ place.name }}</a>
        </li>

        <li class="active">
            <i class="fa fa-table"></i> Create Offer
        </li>
    </ol>
{% endblock %}






{% block content %}





    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-long-arrow-right fa-fw"></i> Offer Information {{ o.name }}</h3>
            </div>
            <div class="panel-body">

                {% if offer_form.errors %}
                <div class="alert alert-danger">
                  <strong>Alert!</strong> Please validate all fields before submitting.
                </div>
                {% endif %}

                {% load crispy_forms_tags %}
                {% crispy offer_form %}



            </div>
        </div>
    </div>


<script>

        $( function() {
            $( "#id_start_date" ).datepicker();
            $( "#id_end_date" ).datepicker();
          } );

        </script>



{% endblock %}

places/templates/offer/offer_detail.html
{% extends "base.html" %}





{% block title %}
    {{ object.name }}
{% endblock %}
{% block head %}{{ object.name }}{% endblock %}
{% block head_subtitle %}{{ object.description }}{% endblock %}
{% block breadcrumb %}

<ol class="breadcrumb">
                                        <li>
                                            <i class="fa fa-home"></i>
                                            <a href="{% url 'list_place' %}">Home</a>
                                        </li>

                                        <li>
                                            <i class="fa fa-list"></i>
                                            <a href="{% url 'list_place' %}">List Places</a>
                                        </li>

                                        <li class="active">
                                            <i class="fa fa-table"></i>
                                            <a href="{% url 'detail_place' object.place.pk %}"> {{ object.place.name }}</a>
                                        </li>

                                        <li class="active">
                                            <i class="fa fa-tags"></i> Offer Detail
                                        </li>
                                    </ol>

{% endblock %}


{% block content %}






        <div class="col-lg-12">

            <div class="panel panel-default">
                            <div class="panel-heading">
                                    <div class="panel-heading clearfix">
                                      <h4 class="panel-title pull-left" style="padding-top: 7.5px;">Offer Detail</h4>
                                          <div class="pull-right">
                                            <a href="#" class="btn btn-primary btn-sm" onclick="updatePlace({{ place.id }}); return false;">Edit</a>
                                            <a href="#" class="btn btn-danger btn-sm" onclick="deletePlace({{ place.id }}); return false;  ">Delete</a>
                                          </div>
                                    </div>
                            </div>
                            <div class="panel-body">

                                <div class="row form-group">
                                    <div class="col-md-6"> <b>Name: </b>{{ object.name }} </div>
                                    <div class="col-md-6"> <b>Description: </b>{{ object.description }} </div>

                                    </div>

                                <div class="row form-group">
                                    <div class="col-md-6"> <b>Start day: </b>{{ object.start_date }} </div>
                                    <div class="col-md-6"> <b>End Day: </b>{{ object.end_date }} </div>

                                    </div>


                                <div class="row">
                                    <div class="col-md-6"> <b>Image thumbnail: </b>
                                        <img class="img-responsive" width="200" height="200" src="{{ object.image.url }}" alt="Image Thumbnail">
                                    </div>
                                    <div class="col-md-6"> <b>Image: </b>
                                        <img class="img-responsive"  src="{{ object.image_thumbnail.url }}" alt="Image">
                                    </div>


                            </div>
                        </div>

            <br/>






        </div>




<script>
function myMap() {
  var myCenter = new google.maps.LatLng({{ place.latitude }},{{ place.longitude }});
  var mapCanvas = document.getElementById("map");
  var mapOptions = {center: myCenter, zoom: 14, scrollwheel: false,};
  var map = new google.maps.Map(mapCanvas, mapOptions);
  var marker = new google.maps.Marker({position:myCenter});
  marker.setMap(map);
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCmz7oHEd5LqSGdal0vtfWUOkxn9GSUKt4&callback=myMap"></script>


<script>
    function deletePlace(id) {
        var ask = window.confirm("Are you sure you want to delete this post?");
        if (ask) {
            //window.alert("This post was successfully deleted.");

            window.location.replace('/places/place/delete/'+id);

        }
    }

    function updatePlace(id) {
         window.location.replace('/places/place/update/'+id);
    }


    function deleteOffer(id) {
        var ask = window.confirm("Are you sure you want to delete this offer?");
        if (ask) {
            //window.alert("This post was successfully deleted.");

            window.location.replace('/places/offer/delete/'+id);

        }
    }


</script>


{% endblock %}